spring:
  application:
    name: hello-service
  profiles:
    active: dev
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8071/}
server:
  port: 9090

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

keycloak:
  realm: spmia-realm
  auth-server-url: http://localhost:8080
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true
  resource: ostock
  credentials.secret: IQdLisO94wrct7cnHaFIwQbguznltLNc
